[package]
name = "canoe-sp1-cc-vkey-bin"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives.workspace = true
clap = { workspace = true, features = ["derive"] }
sp1-sdk.workspace = true
